Disable epam instance deploy because of dockerhub pull limits in epam network
We have errors during requests to download images from dockerhub such as:

```
ERROR: for brn  toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

To mitigate the issue, I temporarly disabled deploy for epam instance.

But in the future, possible solution is move out from dockerhub to some other docker registry, for example github packages https://github.com/features/packages